modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/001damege/ReinforcedAE-dev/issues"

[[mods]]
modId="reinforcedae"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.reinforcedae]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.reinforcedae]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.reinforcedae]]
    modId="ae2"
    mandatory=true
    versionRange="[15.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.reinforcedae]]
    modId="ae2things"
    mandatory=true
    versionRange="[1.2.1,)"
    ordering="AFTER"
    side="BOTH"